[0m10:53:25.295637 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e84510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x122d84090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x122d91410>]}


============================== 10:53:25.298331 | 43236ddd-f6d8-4edd-9f16-7f4234f19117 ==============================
[0m10:53:25.298331 [info ] [MainThread]: Running with dbt=1.9.0
[0m10:53:25.298639 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '~/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:53:25.299053 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kriparammannaraj/Documents/analyticsengineer/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:53:25.410424 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.14627221, "process_in_blocks": "0", "process_kernel_time": 0.139401, "process_mem_max_rss": "102776832", "process_out_blocks": "0", "process_user_time": 0.666893}
[0m10:53:25.410922 [debug] [MainThread]: Command `dbt deps` failed at 10:53:25.410833 after 0.15 seconds
[0m10:53:25.411264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1025e4310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1025e4290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x122d24f10>]}
[0m10:53:25.411572 [debug] [MainThread]: Flushing usage events
[0m10:53:25.759052 [debug] [MainThread]: An error was encountered while trying to flush usage events
